In [57]:
import cv2
import numpy
from keras.models import load_model
from keras.preprocessing import image

In [58]:
check_model=load_model('face_detection.h5')

In [59]:
camera=cv2.VideoCapture(0)

In [55]:
while 1:
    status,photo=camera.read()
    test_image=cv2.resize(photo,dsize=(224,224), interpolation=cv2.INTER_CUBIC)
    image_test=numpy.expand_dims(test_image,axis=0)
    
    output=check_model.predict(image_test)
    #print(check_model.predict(image_test))

    if output[0][0]>= output[0][1] :
        print(check_model.predict(image_test))
        texted_image =cv2.putText(img=photo, text="ANKUSH", org=(50,400),fontFace=2, fontScale=2, color=(0,0,255), thickness=3)
    elif output[0][0] < output[0][1] :
        print(check_model.predict(image_test))
        texted_image =cv2.putText(img=photo, text="ARTI", org=(50,400),fontFace=2, fontScale=2, color=(0,255,0), thickness=3)
        
    cv2.imshow("VIDEO",texted_image)
    cv2.waitKey(10)
    if cv2.waitKey(100) == 13:
        break
        
        
        
cv2.destroyAllWindows()
camera.release()

[[0.9950488  0.05268823]]
[[0.9972869  0.01128889]]
[[9.999993e-01 4.371687e-07]]
[[0.99923813 0.00267108]]
[[9.9999893e-01 2.3350945e-06]]
[[9.9999154e-01 4.4489825e-05]]
[[9.9998033e-01 6.3928979e-05]]
[[9.999999e-01 1.939849e-07]]
[[9.9998319e-01 2.0058887e-05]]
[[0.9921822  0.02331646]]
[[0.99898857 0.00327841]]
[[9.9996984e-01 4.4156212e-05]]
[[0.9992424  0.00122237]]
[[0.9983682  0.00477326]]
[[9.9981505e-01 2.6185505e-04]]
[[9.9972039e-01 4.4819937e-04]]
[[9.9953401e-01 6.4485933e-04]]
[[9.9997520e-01 3.3232573e-05]]
[[9.9998629e-01 1.6091768e-05]]
[[9.9999821e-01 2.6446178e-06]]
[[9.9997854e-01 3.2444939e-05]]
[[9.9997580e-01 4.1633055e-05]]
[[9.9999940e-01 6.3007536e-07]]
[[9.999995e-01 4.432801e-07]]
[[9.9986053e-01 2.7101944e-04]]
[[9.9980515e-01 3.3399125e-04]]
[[9.9999666e-01 3.2064895e-06]]
[[1.000000e+00 1.748692e-08]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[9.9999416e-01 2.6381742e-06]]
[[9.9999988e-01 4.3262798e-08]]


In [47]:
output[0]

array([9.9999940e-01, 1.4878246e-07], dtype=float32)

In [63]:
    photo1=cv2.imread('ankush.jpg')
    test_image1=cv2.resize(photo1,dsize=(224,224), interpolation=cv2.INTER_CUBIC)
    image_test1=numpy.expand_dims(test_image1,axis=0)
    
    output1=check_model.predict(image_test1)
    #print(check_model.predict(image_test))

    if output1[0][0]>= output1[0][1] :
        print(check_model.predict(image_test1))
        texted_image1 =cv2.putText(img=photo1, text="ANKUSH", org=(50,400),fontFace=2, fontScale=2, color=(0,0,255), thickness=3)
    elif output1[0][0] < output1[0][1] :
        print(check_model.predict(image_test1))
        texted_image1 =cv2.putText(img=photo1, text="ARTI", org=(50,400),fontFace=2, fontScale=2, color=(0,255,0), thickness=3)

[[9.9998045e-01 8.7776807e-06]]
